---
title: "Exploratory Analysis"
output: html_document
---

## The Study of Sleep and Work

### Authors

Leon Nguyen, Samarth Rao, Nicholas Chung, Jonathan Cao

### Date

Spring 2024

### Abstract

Our main question is how sleep amount correlates to someone’s earnings and age. To address this question we will be analyzing a dataset containing important statistics regarding factors such as the amount of sleep, age, time spent on work, etc.. We are concerned with this because there is a notion that wealthy people give up sleep to further their careers so we plan to analyze the data, and compare how work-life balance affects sleep patterns. 

### Keywords

* Sleep amount
* Age
* Work-life Balance
* Work relationship

### Introduction  

This project aims to find a correlation between the amount of sleep a person gets and work. Does age increase or decrease the amount of sleep a person gets? How does the nature of one's job, particularly the level of work experience, affect sleep patterns? We will be exploring these questions to challenge the notion often perpetuated by successful individuals that sacrificing sleep is necessary to maximize career potential. On social media, it's common to see influential business people, often making six-figure salaries, advocating for waking up before dawn and maintaining a sleep schedule that includes only 4-6 hours of rest per night, far below the amount recommended by scientists. These influencers swear by their schedules and guarantee success to those who follow their routines. However, this project seeks to explore the potential negative effects of such advice, especially for young, impressionable viewers. Consistently sacrificing sleep can impair daily functioning and long-term health. By answering these questions, we hope to provide a clearer understanding of how different levels of work experience impact sleep, thereby guiding individuals towards finding a sleep schedule that is both healthy and conducive to their career goals.

> Where did you find the data? Please include a link to the data source  

* The data set we’re using was found on [Kaggle](https://www.kaggle.com/datasets/kapturovalexander/sleep-patterns?resource=download)